# Name = Mussawir Sohail
# Course = DS
# Assignment = 8
# Date = 21.10.2025

# EXCISE NUMPY


In [ ]:
#47
import numpy as np

zeros_array = np.zeros(10)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#48
ones_array = np.ones(5)
result = ones_array * 10
print(result)

[10. 10. 10. 10. 10.]


In [ ]:
#49
array_0_to_50 = np.arange(0, 51, 5)
print(array_0_to_50)

[ 0  5 10 15 20 25 30 35 40 45 50]


In [ ]:
#50
random_array = np.random.randint(1, 101, size=100)
print("Array:", random_array)
print("Minimum:", random_array.min())
print("Maximum:", random_array.max())

Array: [ 38  91  90  84  50  15  55  17  26   8  42  84  33  81  75  30  68  99
  80  89  10  73   3  48  58  12  60   8  64  96  20  13  63  75  11  96
  84  53  40  29  71  38  65  85  31  94  35  43   7  70 100  53  68  31
  50  98  75  83  25  63  40  94  55  66  56  16  23  87  86  82  75   9
   9  72  51  28  79  76  41  46  22  46   7  93  97  15  60  26  21  83
  81  27  19   7  22  95  86  14  57  75]
Minimum: 3
Maximum: 100


In [ ]:
#51
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

addition = arr1 + arr2
multiplication = arr1 * arr2

print("Addition:", addition)
print("Multiplication:", multiplication)

Addition: [5 7 9]
Multiplication: [ 4 10 18]


In [ ]:
#52
array_2d = np.random.rand(3, 3)  # random floats between 0 and 1
print("2D Array:\n", array_2d)
print("Mean:", array_2d.mean())

2D Array:
 [[0.0975889  0.957963   0.01971791]
 [0.80583669 0.88524798 0.47247837]
 [0.60262184 0.2893533  0.2144096 ]]
Mean: 0.48280195558761335


In [ ]:
#53
array_4x5 = np.arange(20).reshape(4, 5)
reshaped_array = array_4x5.reshape(5, 4)
print("Original Array:\n", array_4x5)
print("Reshaped Array:\n", reshaped_array)

Original Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [ ]:
#54
arr = np.array([1, 7, 3, 9, 5])
max_index = arr.argmax()
print("Index of maximum value:", max_index)

Index of maximum value: 3


# Pandas Exercises

In [ ]:
#55
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [20, 22, 21],
    "Score": [95, 82, 88]
}

df = pd.DataFrame(data)
print(df)

      Name  Age  Score
0    Alice   20     95
1      Bob   22     82
2  Charlie   21     88


In [ ]:
#56
print(df["Name"])


0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object


In [ ]:
#57
def grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    else:
        return "D"

df["Grade"] = df["Score"].apply(grade)
print(df)

      Name  Age  Score Grade
0    Alice   20     95     A
1      Bob   22     82     B
2  Charlie   21     88     B


In [ ]:
#58
high_scores = df[df["Score"] > 85]
print(high_scores)

      Name  Age  Score Grade
0    Alice   20     95     A
2  Charlie   21     88     B


In [ ]:
#59
mean_score = df["Score"].mean()
median_score = df["Score"].median()

print("Mean Score:", mean_score)
print("Median Score:", median_score)

Mean Score: 88.33333333333333
Median Score: 88.0


In [ ]:
#60
df_csv = pd.read_csv("DATA.csv")
print(df_csv.head())

      Name  Age  Score Grade
0    Alice   20     92     A
1      Bob   22     85     B
2  Charlie   21     78     C
3    David   23     90     A
4     Emma   20     88     B
